language: go

sudo: false

install:
  - source .default.env
  - go get ./...
  - go get github.com/golang/lint/golint
  - go get github.com/kisielk/errcheck
  - go get github.com/joho/godotenv
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/modocache/gover
  - go get -u github.com/mattn/goveralls

jobs:
  include:
    - stage: verification
      go: 1.9
      script: make verification

    - stage: test
      go: 1.9
      script:
        - make test-coverage
        - gover
        - goveralls -service=travis-ci -coverprofile=gover.coverprofile

    - stage: test
      go: 1.8
      script: make test
