language: go

go:
  - 1.8

sudo: false

before_install:
  - go get github.com/golang/lint/golint

script:
  - source .default.env
  - go vet ./...
  - golint -set_exit_status ./...
  - go get github.com/kisielk/errcheck && CGO_ENABLED=0 errcheck ./...
  - go test -parallel 15 -v ./...
