language: go

go:
  - 1.8

sudo: false

install:
  - source .default.env
  - go get ./...
  - go get github.com/golang/lint/golint
  - go get github.com/kisielk/errcheck
  - go get github.com/joho/godotenv

jobs:
  include:
    - stage: verification
      script: make verification

    - stage: test
      script: make test