language: go

go:
  - 1.8

sudo: false

install:
  - source .default.env
  - go get github.com/golang/lint/golint

jobs:
  include:
    - stage: verification
      script:
        - go vet ./...
        - golint -set_exit_status ./...
        - go get github.com/kisielk/errcheck && CGO_ENABLED=0 errcheck ./...

    - stage: test
      script:
        - go test -parallel 5 -v ./...